### ISSUE TITLE
Styling problem in new subscription view

### ISSUE THREAD

**Issue by krichtof** [Association-Merci-Edgar/Merci-Edgar#103]
Problem in heroku (wip env), not in dev
It should display plans in round like in dev, but it does'nt

![screenshot_new_subscription_dev](https://cloud.githubusercontent.com/assets/1111966/10370190/19abee1e-6dde-11e5-91a7-ca63562780c3.png)

![screenshot_new_subscription_heroku_wip](https://cloud.githubusercontent.com/assets/1111966/10370036/8024f952-6ddd-11e5-87e1-5e493527dcb8.png)

**Comment by krichtof** [comment]
Any idea @yaf ?

**Comment by yaf** [comment]
None now. I need to try in local env to see

**Comment by krichtof** [comment]
Ok. I'm sure you'll have an idea after trying in local env @yaf  ;)

**Comment by yaf** [comment]
J'ai pas encore essayé :-)

**Comment by krichtof** [comment]
Le problème était simplement dû au fait que les assets n'étaient pas précompilés.
J'avais oublié qu'actuellement, les assets sont précompilés en local, et pas par heroku...

**Comment by yaf** [comment]
Attention, les assets devrait être compilé par Heroku ! https://devcenter.heroku.com/articles/rails-asset-pipeline Si les assets ne compile pas sur heroku, c'est un autre soucis qu'il faut résoudre :-)

**Comment by krichtof** [comment]
D'accord avec toi sur le principe. Mais il se trouve que les assets étaient précompilés en local depuis pas mal de temps. Je propose donc de fermer cette issue et d'en ouvrir une autre plus général sur le fait qu'il faut changer notre façon de précompiler les assets.

**Comment by yaf** [comment]
ok
