### ISSUE TITLE
Bug detected / Visite Guidée.

### ISSUE THREAD

**Issue by ghost** [Association-Merci-Edgar/Merci-Edgar#109]
Problème trouvé lors de la première connexion au site qui bloque la page Bienvenue lors de la visite guidée. Même après une déconnexion, le visite guidée est toujours là et continue de bloquer la page.
http://www.noelshack.com/2015-45-1446741394-bug-reported-bienvenue.jpeg

**Comment by Em-AK** [comment]
Le problème arrive à l'étape de présentation du "bouton +"

**Comment by krichtof** [comment]
Merci @nicolastessier d'avoir remonté ce bug.

**Comment by yaf** [comment]
Non reproduit. Corrigé par ailleurs ?
