### ISSUE TITLE
Impossible d'importer un fichier

### ISSUE THREAD

**Issue by krichtof** [Association-Merci-Edgar/Merci-Edgar#132]
Un problème survient lors d'un import de fichier.
Pour des raisons de confidentialité, merci de me demander le fichier pour celles et ceux qui souhaiteraient reproduire le problème en vue de le corriger.

**Comment by krichtof** [comment]
Je tiens à ta disposition le fichier @yaf si besoin ;)

**Comment by yaf** [comment]
Tu peux pas essayer de le mettre ici ? Ou juste le morceau qui fait mal (si tu l'as identifié) ?

**Comment by krichtof** [comment]
@yaf Je n'ai pas identifié le morceau qui fait mal. Pas possible de le mettre ici, il y a possiblement des numéros de téléphone privés.

**Comment by krichtof** [comment]
@yaf J'ai réussi à reproduire le bug en local. Et pour info, j'ai une piste 
Une exception est trappée dans contacts_import_worker en ligne 40 :
undefined method `delete_after_store' for #<Contact:0x007fd632aa99b0>

**Comment by yaf** [comment]
Je viens de voir un truc, qui date de je ne sais pas trop quand ... Un oubli, genre appel de la méthode `delete_after_store` dans le ! alors que la definition (un peu plus bas) : `def delete_after_store!`... 

L'appel est dans une grosse méthode un peu dégueux, j'ai pas prit le temps de mettre un test dessus, mais ça vaudrais le coup de faire un bon refactoring.

A tester avec le fichier.

**Comment by krichtof** [comment]
Je viens de tester avec le fichier. C'était effectivement le problème :) Merci !
Je viens de déployer en prod ton commit.

D'accord avec toi sur le refactoring ...
