### ISSUE TITLE
Festival without scheduling are not exported

### ISSUE THREAD

**Issue by krichtof** [Association-Merci-Edgar/Merci-Edgar#78]
This case can happen.
In production, there is 112 festivals without schedulings (total festivals : 2358)

**Comment by krichtof** [comment]
To solve this, here is my proposal : 

At the moment, `Structure.export` exports only generic structures. We could change it and export all the structures (generic structures, venues and festivals)

Any opinion ?

**Comment by yaf** [comment]
Add a festival export. It's enough. When festival will be merge with scheduling, we will just remove this class.

**Comment by krichtof** [comment]
In fact, I think it's easier at the moment (just one line to update in `Structure.export`)
All structures in one export file.
All people in one export file.
A specific file for schedulings.
A specific file for room venues.

**Comment by yaf** [comment]
just do it then :-p

**Comment by krichtof** [comment]
Yes :) :) :)

**Comment by krichtof** [comment]
Done with https://github.com/Association-Merci-Edgar/Merci-Edgar/pull/82
