### ISSUE TITLE
No mail received after contacts export

### ISSUE THREAD

**Issue by krichtof** [Association-Merci-Edgar/Merci-Edgar#86]
No mail received after contacts export.
Weird because in sidekiq, the job is completed, no failed job.
In log, I see : email sent

**Comment by krichtof** [comment]
Still investigating ...
Email after export works in local env, but not in wip environment.
(and FYI, email after import works in wip env)

**Comment by yaf** [comment]
Look into mailchimp website. You certainly have trace there

**Comment by krichtof** [comment]
I already had a look on mandril admin interface. And no trace about it :(

**Comment by krichtof** [comment]
Fixed with this commit d99da8ee4af066f94194e4acde02ad7ce752e799
